<?php

return array (
  'name' => '外贸云',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.2',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'cms',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'user' => '会员配置',
    'backend' => '后台配置',
    'cms' => 'CMS配置',
    'gbook' => '留言配置',
    'superadmin' => '超级管理员',
    'translate' => '翻译',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '496631085@qq.com',
  'mail_smtp_pass' => 'yuqbwstnyfocbjci',
  'mail_verify_type' => '2',
  'mail_from' => '496631085@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'login_captcha' => '1',
  'usercenter' => '1',
  'mobile_switch' => '1',
  'tel' => '1999999999',
  'index_url' => '/',
  'email' => '496631085@qq.com',
  'addr' => '无锡滨湖区9-3',
  'addr2' => '联系地址可以删除',
  'banquan' => 'By 无锡网科',
  'technical_support' => '无锡网科信息科技有限公司',
  'route_switch' => '1',
  'copy_protection' => '1',
  'logo' => '/cms/images/logo.png',
  'ban_switch' => '1',
  'ban_cachetime_multiple' => '2',
  'keywords' => '网科CMS 无锡网科',
  'description' => '无锡网科信息科技有限公司 无锡网科',
  'add_gbook_switch' => '1',
  'gbook_email' => 'you_email@qq.com',
  'gbook_to_email_switch' => '1',
  'gbook_captcha_switch' => '1',
  'cms_seo_switch' => '1',
  'config_group_show' => 'basic|cms|gbook',
  'config_field_hide' => 'version|timezone|forbiddenip|languages',
  'head_code' => NULL,
  'contacts' => 'xiaohe',
  'update_cate_to_auth_rule' => '0',
  'cms_link_not_menu' => '1',
  'default_auth_rule_pid' => '',
  'crud_copy_switch' => '0',
  'link_auto_hide' => '1',
  'baidu_app_id' => '20241130002215359',
  'baidu_app_secret' => 'mfLn2xHTbgVeRwY250n1',
  'fanyi_app' => 'baidu',
);
